version: "2"
services:
  fileuploadserver:
    build:
      context: ./fileuploader_jar
    volumes:
    - ./fileuploader_jar:/fileuploader
    ports:
      - "8081:8080"
    depends_on:
      - kafka
  lighttpd:
    image: sebp/lighttpd
    volumes:
      - ./clientsender:/var/www/localhost/htdocs
    ports:
      - "80:80"
    depends_on:
      - webpack
      - fileuploadserver

  webpack:
    image: node:10-alpine
    volumes:
        - ./webpack:/app
        - ./webpack/node_modules:/node_modules
        - ./webpack/package.json:/package.json
        - ./webpack/webpack.config.js:/webpack.config.js
        - ./webpack/js:/js
    ports:
      - "8085:8085"
    depends_on:
      - fileuploadserver
    working_dir: /app
    command: ["npm", "start"]
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - "29092:29092"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://127.0.0.1:29092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_HOST://:29092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-rest:
    image: nodefluent/kafka-rest:latest
    ports:
      - 8082:8082
    links:
      - kafka
      - zookeeper
    depends_on:
      - kafka
      - zookeeper
    environment:
      DEBUG: "*"

  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    hostname: kafka-topics-ui
    ports:
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest:8082/"
      PROXY: "true"
    depends_on:
      - zookeeper
      - kafka
      - kafka-rest
